# Generated by Django 2.2 on 2021-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_auto_20210402_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
