# Generated by Django 2.2 on 2021-04-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_region_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Town',
        ),
    ]
