# Generated by Django 2.2 on 2021-04-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_auto_20210405_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='neighbour',
            field=models.ManyToManyField(related_name='_region_neighbour_+', to='pg.Region'),
        ),
        migrations.AlterField(
            model_name='town',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='pg.District'),
        ),
    ]
